name: hng13_country_currency

services:
  api:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./cache:/app/cache

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: pepa-linha-dark
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:9.5.0
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
